CREATE TABLE RAPEECH_TEST  (
	ID BIGINT NOT NULL PRIMARY KEY,
	NAME VARCHAR(50)
) ;

INSERT INTO RAPEECH_TEST (ID, NAME) VALUES (1, 'Alice');
INSERT INTO RAPEECH_TEST (ID, NAME) VALUES (2, 'Bob');
INSERT INTO RAPEECH_TEST (ID, NAME) VALUES (3, 'Charlie');